//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopeBank.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HopeBank.SQL.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin tran
        ///declare @error int=1
        ///update [balance] set amount=amount-@amount,@error=0 where account_id=@account_from and amount&gt;=@amount-maxcredit
        ///if(@error=0)
        ///begin 
        ///  update [balance] set amount=amount+@amount,@error=0 where account_id=@account_to
        ///  insert into [dbo].[transact](id,account_from,account_to,amount,extern_account,detail)
        ///  values (@id,@account_from,@account_to, @amount, @extern_account, @detail)
        ///end;
        ///commit tran
        ///select @error;.
        /// </summary>
        public static string create_transact {
            get {
                return ResourceManager.GetString("create_transact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   
        ///CREATE TABLE [dbo].[account](
        ///[id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///[phone] [varchar](30) NOT NULL,
        ///[email] [varchar](100) NOT NULL,
        ///[passhash] [varchar](100) NOT NULL,
        ///[firstname] [varchar](100) NOT NULL,
        ///[lastname] [varchar](100) NOT NULL,
        ///[isadmin] [bit] NOT NULL default 0);
        ///
        ///CREATE TABLE [dbo].[balance](
        ///[account_id] [int] NOT NULL primary key,
        ///[amount] [bigint] NOT NULL,
        ///[maxcredit] [bigint] NOT NULL);
        ///
        ///CREATE TABLE [dbo].[transact](
        ///[id] [bigint] NOT NULL,
        ///[account_from] [ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FillDb {
            get {
                return ResourceManager.GetString("FillDb", resourceCulture);
            }
        }
    }
}
